variables:
  BUILD_DOCKER_ARG_ENTRYPOINT: mkdocs-partial
  BUILD_DOCKER_ARG_VERSION_FILE: mkdocs_partial/version.py
  BUILD_PUBLISH_DOCKER_IMAGE: true
  BUILD_DOCKER_ARG_COVERAGE_THRESHOLD: 0
  BUILD_DOCKER_ARG_WORKING_DIR: "/docs"
  BUILD_DOCKER_ARG_PYINSTALLER_EXTRA_ARGS: "--collect-all jinja2"
  BUILD_FINAL_TARGET: "final-pyinstaller"
  BUILD_DOCKER_ARG_DOCS_DIRECTORY: "documentation/partial"
  BUILD_DOCKER_ARG_DOCS_TITLE: "Partial Documentation"
  TRIGGER_PROJECTS: "$GITLAB_ROOT_GROUP_PATH/subsystems/documentation/docs-site-documentation-inceptum $GITLAB_ROOT_GROUP_PATH/subsystems/documentation/docs-site-documentation-exordis"
  # GITHUB_SYNC_CONFIG: |
  #   exordis/mkdocs-partial master
  #   exordis/sponsors-mkdocs-partial master vNext
  GITHUB_SYNC_CONFIG: |
    exordis/test_public master
    exordis/test_sponsors master vNext
include:
  - project: $GITLAB_CICD_TEMPLATES_PROJECT_PATH
    file: 'lib-python.yml'
    
    
    
    
    
    
    
