variables:
  BUILD_DOCKER_ARG_ENTRYPOINT: mkdocs-partial
  BUILD_DOCKER_ARG_VERSION_FILE: mkdocs_partial/version.py
  BUILD_PUBLISH_DOCKER_IMAGE: true
  BUILD_DOCKER_ARG_COVERAGE_THRESHOLD: 0
  BUILD_DOCKER_ARG_WORKING_DIR: "/docs"
  BUILD_DOCKER_ARG_PYINSTALLER_EXTRA_ARGS: "--collect-all jinja2"
  BUILD_DOCKER_IMAGE_NAME: "exordis/mkdocs-partial"
  DOCS_DOCKER_ARG_DOCS_DIRECTORY: "documentation/partial"
  DOCS_DOCKER_ARG_DOCS_TITLE: "Partial Documentation"
  TRIGGER_PROJECTS: "$GITLAB_ROOT_GROUP_PATH/subsystems/documentation/docs-site-documentation-inceptum $GITLAB_ROOT_GROUP_PATH/subsystems/documentation/docs-site-documentation-exordis"
  DOCS_DOCKER_ARG_DOCUMENTATION_VERIFY_WITH_SITE_PACKAGES: "documentation-inceptum documentation-exordis"
  DOCS_DOCKER_ARG_EXTRA_APK_PACKAGES: cairo
  VERSIONING_STRATEGY: gitflow
  GITHUB_SYNC_CONFIG: |
    exordis/mkdocs-partial master
    exordis/sponsors-mkdocs-partial master vNext
  # GITHUB_SYNC_CONFIG: |
  #   exordis/test_public master
  #   exordis/test_sponsors master vNext
include:
  - project: $GITLAB_CICD_TEMPLATES_PROJECT_PATH
    file: 'lib-python.yml'
    inputs:
      github_sync: true
      pypi_public_registry: pypi
      docker_public_registry_source: https://github.com/exordis/mkdocs-partial
      docker_internal_registry_source: https://github.com/exordis/sponsors-mkdocs-partial
      final_target: "final-pyinstaller"
      
      